# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionworkorderinfo',
            name='db_host',
            field=models.UnsignedIntegerField(default='1000000'),
        ),
    ]
