# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='emails',
            field=models.CharField(max_length=100),
        ),
    ]
